main: dk.muj.derius.parkour.DeriusAcrobatics
name: Derius-Parkour
version: 0.1_dev
#website: http://muj.dk/Derius
authors: [madus]
description: §eDerius is an open skill framework
depend: [Derius-Core]
